### ISSUE TITLE
Unexpected draw behaviour

### ISSUE THREAD

**Issue by umer322** [4Q-s-r-o/signature#58]
If i set signature inside expanded in row widget and don't specify width i am able to draw out side of signature widget.
For test purpose:
                        `Row(
                    children: [
                      Expanded(child: AutoSizeText("Citizen Signature")),
                      Flexible(
                        flex: 2,
                        child: 
                          Signature(
                            controller: SignatureController(
                              penStrokeWidth: 5,
                              penColor: Colors.black,
                              exportBackgroundColor: Colors.blue,
                            ),
                            height: height * 0.1,
                            backgroundColor: Colors.grey[300]!,
                          )
                      )
                    ],
                  )`

**Comment by cihancil** [comment]
Same here. If I don't set a width and height for Signature widget, I can draw outside of its border. It doesn't need to be inside Row.

**Comment by MartinHlavna** [comment]
Fix released in ```5.0.1```

**Comment by cfsbhawkins** [comment]
I don't think this is fixed. Using 5.0.1, even added a row and flexible around it like in sample.

![Screenshot_1652820904](https://user-images.githubusercontent.com/14224435/168908573-6908b76b-437c-4b9c-b4be-c536962931bd.png)

 return Column(children: [
      Row(
        children: [
          Flexible(
              flex: 2,
              child: Signature(
                controller: _signatureController,
                backgroundColor: CoreTheme.gray,
                height: 100,
              ))
        ],
      ),
      Padding(
        padding: const EdgeInsets.symmetric(horizontal: 8.0),
        child: TextFormField(
            minLines: 1,
            maxLines: 1,
            textCapitalization: TextCapitalization.words,
            keyboardType: TextInputType.name,
            decoration: InputDecoration(
              hintText: 'Type Signatory Name',
              hintStyle: CoreTheme.textStyleParagraph(color: FontColor.gray),
              border: InputBorder.none,
            ),
            onSaved: (name) => onValueChanged(context, name: name)
        ),
      ),
      Divider(thickness: 1),
    ]);

**Comment by rivella50** [comment]
Same here, still doesn't work.
Signature seems to be open to the right and bottom side, even when i set a width value.
![Screenshot 2022-05-23 at 07 23 53](https://user-images.githubusercontent.com/54292/169749069-983b093c-9179-44a3-b56a-440b2363ce99.png)

```Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    children: [
                      const SizedBox(
                        height: 30,
                      ),
                      Signature(
                        controller: _companySignatureController,
                        height: 150,
                        backgroundColor: Colors.grey,
                      ),
```

Is there a hack to fix this on our side or a package version to go down in order that this works again meanwhile?

**Comment by maddionatoplus** [comment]
Same as me, I am drawing everywhere. Really a big problem for me. What can I do?

**Comment by cfsbhawkins** [comment]
> 

The workaround I did was, I made it a full screen landscape view problem solved for my use case.

**Comment by rivella50** [comment]
Not possible for me since i have to offer 2 signature areas in my view.
If the developer is not able to react soon i will have to find another package or implement this feature by myself.

**Comment by rivella50** [comment]
My hack solution is the following: I adjusted function SignatureState::_addPoint like this:
```
final myWidth = widget.width ?? screenSize!.width;
final myHeight = widget.height ?? screenSize!.height;

//SAVE POINT ONLY IF IT IS IN THE SPECIFIED BOUNDARIES
if (o.dx > 0 && o.dx < myWidth &&
    o.dy > 0 && o.dy < myHeight) {
```
And when defining a height and width explicitely or implicitely (e.g. by using a LayoutBuilder around Signature) it seems to work for me. 
The problem with the original code seems to be that it doesn't take into account the optionally defined width and height parameters, which both are <= their screenSize pendants, and if they are smaller drawing across the right and bottom borders is possible.

**Comment by alex-cp360** [comment]
I have solved this issue by using **ClipRect** as the parent for the **Signature** widget
![Screenshot 2022-06-14 at 12 37 17 PM](https://user-images.githubusercontent.com/88377983/173515185-2db98646-b25b-4864-afaa-2c2204b3d935.png)
.
