### ISSUE TITLE
exportBackgroundColor: Colors.transparent  is not working.

### ISSUE THREAD

**Issue by laopaoer-wallet** [4Q-s-r-o/signature#86]
exportBackgroundColor: Colors.transparent  is not working.

**Comment by jtaylor-dohle** [comment]
Having the same issue.  `exportBackgroundColor: Colors.transparent` is causing image to be exported with black background.

Not sure how to figure out when this bug was introduced, this project has no tags!

**Comment by hasbean** [comment]
I am suddenly having this issue as well with form_builder_extra_fields.  What made it worse was that I was using a black pen color and had no clue what was going on as it all showed up as black.

Resorting to using white background now.

--edit:
Forgot to mention, I'm running this on the web.

I've worked around it by exporting the image instead:
```
var image = (await _controller.toImage())!;

if (image == null) return;

var bytes = (await image.toByteData(format: ImageByteFormat.png))!.buffer.asUint8List();
```

**Comment by MartinHlavna** [comment]
Issue affects web only. Fix will be released soon.

**Comment by MartinHlavna** [comment]
Fixed in ```5.4.0```

**Comment by AlexPopaUpcode** [comment]
I have the same issue on Android. The 5.4.0 version doesn't fix the problem
